<map version='1.0.1'><node TEXT='Double Click to Edit' CREATED='1756820829920' ID='ID_root' MODIFIED='1756820829920'><depth>0</depth><icon/><image/><imageSize/><node TEXT='Cyber Enablers
(EN)
Personnel who perform work roles to support or facilitate the functions of cyber-IT, cybersecurity, cyberspace effects, or intelligence workforce (cyberspace) work roles. This includes actions to support acquisition, training and leadership activities.' CREATED='1756820829922' ID='ID_mf2lrg0ybcm0uus8p5e' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='OVERSIGHT and GOVERNANCE (OG) – Provides leadership, management, direction, and advocacy so the organization may effectively manage cybersecurity-related risks to the enterprise and conduct cybersecurity work. ' CREATED='1756820829922' ID='ID_mf2lrg0yyqmse2r337j' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='Training / Education' CREATED='1756820829922' ID='ID_mf2lrg0ycsqcu5iqedp' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/><node TEXT='(711) (OG-WRL-004) Cyber Instructional Curriculum Developer
Develops, plans, coordinates, and evaluates cyber training/education courses, methods, and techniques based on instructional needs.' CREATED='1756820829922' ID='ID_mf2lrg0y5nt6m2mzbfu' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(712) (OG-WRL-005) Cyber Instructor
Develops and conducts training or education of personnel within cyber domain. ' CREATED='1756820829922' ID='ID_mf2lrg0ynzr649hs1t' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node></node><node TEXT='Acquisition Management' CREATED='1756820829922' ID='ID_mf2lrg0y8199rgm94c2' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/><node TEXT='(801) (OG-WRL-010) Program Manager
Leads, coordinates, communicates, integrates and is accountable for the overall success of the program, ensuring alignment with critical agency priorities.' CREATED='1756820829922' ID='ID_mf2lrg0yod3uk7q94mf' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(802) (OG-WRL-011) IT Project Manager
Work that involves directly managing information technology projects to provide a unique service or product.' CREATED='1756820829922' ID='ID_mf2lrg0yq73id08577' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(803) (OG-WRL-009) Product Support Manager 
Manages the package of support functions required to field and maintain the readiness and operational capability of systems and components. ' CREATED='1756820829922' ID='ID_mf2lrg0yucecjgm47h' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(804) (OG-WRL-015) IT Investment/Portfolio Manager
Manages a portfolio of IT capabilities that align with the overall needs of mission and business enterprise priorities.' CREATED='1756820829922' ID='ID_mf2lrg0yp0gw0hgu8w' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(805) (OG-WRL-016) IT Program Auditor
Conducts evaluations of an IT program or its individual components, to determine compliance with published standards. ' CREATED='1756820829922' ID='ID_mf2lrg0yjosn00twht' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node></node><node TEXT='Executive Leadership' CREATED='1756820829922' ID='ID_mf2lrg0ydjdhoe63jbc' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/><node TEXT='(732) (OG-WRL-008) Privacy Compliance Manager
Develops and oversees privacy compliance program and privacy program staff, supporting privacy compliance needs of privacy and security executives and their teams.' CREATED='1756820829922' ID='ID_mf2lrg0ygwcvl5coz7e' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(751) (OG-WRL-003) Cyber Workforce Developer and Manager
Develop cyberspace workforce plans, strategies and guidance to support cyberspace workforce manpower, personnel, training and education requirements and to address changes to cyberspace policy, doctrine, materiel, force structure, and education and training requirements. ' CREATED='1756820829922' ID='ID_mf2lrg0yhpxxqu4qrrg' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(752) (OG-WRL-002) Cyber Policy and Strategy Planner
Develops cyberspace plans, strategy and policy to support and align with organizational cyberspace missions and initiatives. ' CREATED='1756820829922' ID='ID_mf2lrg0y0zgbf9ffsnds' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(901) (OG-WRL-007) Executive Cyber Leader
Executes decision-making authorities and establishes vision and direction for an organization&apos;s cyber and cyber-related policies, resources, and/or operations, while maintaining responsibility for risk-related decisions affecting mission success.' CREATED='1756820829922' ID='ID_mf2lrg0yac7vx5qt45p' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node></node><node TEXT='Legal / Law Enforcement' CREATED='1756820829922' ID='ID_mf2lrg0ymzalv6a44t' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/><node TEXT='(731) (OG-WRL-006) Cyber Legal Advisor
Provides legal advice and recommendations on relevant topics related to cyber law. ' CREATED='1756820829922' ID='ID_mf2lrg0yrkwcnzbqu3m' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node></node></node><node TEXT='INVESTIGATION (IN) – Conducts national cybersecurity and cybercrime investigations, including the collection, management, and analysis of digital evidence.' CREATED='1756820829922' ID='ID_mf2lrg0ydrzaut300gs' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='Legal / Law Enforcement' CREATED='1756820829922' ID='ID_mf2lrg0y9upxyd5mcj6' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/><node TEXT='(211) (IN-WRL-002) Forensics Analyst
Conducts deep-dive investigations on computer-based crimes establishing documentary or physical evidence, to include digital media and logs associated with cyber intrusion incidents.' CREATED='1756820829922' ID='ID_mf2lrg0y132azz3mmrs' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node><node TEXT='(221) (IN-WRL-001) Cyber Crime Investigator
Identifies, collects, examines, and preserves evidence using controlled and documented analytical and investigative techniques.' CREATED='1756820829922' ID='ID_mf2lrg0ylvnczt2stt' MODIFIED='1756820829922'><depth>4</depth><icon/><image/><imageSize/></node></node></node></node><node TEXT='Information Technology
(IT)
Personnel who design, build, configure, operate, and maintain IT, networks, and capabilities. This includes actions to prioritize implement, evaluate, and dispose of IT as well as information resource management, and the management, storage, transmission, and display of data and information.' CREATED='1756820829922' ID='ID_mf2lrg0y1871infc0zgi' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='IMPLEMENTATION and OPERATION (IO) – Provides implementation, administration, configuration, operation, and maintenance to ensure effective and efficient technology system performance and security' CREATED='1756820829922' ID='ID_mf2lrg0ymbvvbxseded' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(411) (IO-WRL-007) Technical Support Specialist
Provides technical support to customers who need assistance utilizing client level hardware and software in accordance with established or approved organizational process components. (i.e., Master Incident Management Plan, when applicable).' CREATED='1756820829922' ID='ID_mf2lrg0yo9p6u55ca3k' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(421) (IO-WRL-002) Database Administrator
Administers databases and/or data management systems that allow for the storage, query, and utilization of data.' CREATED='1756820829922' ID='ID_mf2lrg0yzakss1f1v5g' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(431) (IO-WRL-003) Knowledge Manager
Responsible for the management and administration of processes and tools that enable the organization to identify, document, and access intellectual capital and information content.' CREATED='1756820829922' ID='ID_mf2lrg0yjmgdf28i978' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(441) (IO-WRL-004) Network Operations Specialist
Plans, implements, and operates network services/systems, to include hardware and virtual environments.' CREATED='1756820829922' ID='ID_mf2lrg0yqbmv55pk2u' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(451) (IO-WRL-005) System Administrator
Installs, configures, troubleshoots, and maintains hardware, software, and administers system accounts.' CREATED='1756820829922' ID='ID_mf2lrg0yghd2znp3e5a' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='DESIGN and DEVELOPMENT (DD) – Conducts research, conceptualizes, designs, develops, and tests secure technology systems, including on perimeter and cloud-based networks. ' CREATED='1756820829922' ID='ID_mf2lrg0yyhc8y58x70f' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(632) (DD-WRL-004) Systems Developer 
Designs, develops, tests, and evaluates information systems throughout the systems development lifecycle.' CREATED='1756820829922' ID='ID_mf2lrg0y24qgh9sgl3r' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(641) (DD-WRL-006) Systems Requirements Planner 
Consults with customers to evaluate functional requirements and translate functional requirements into technical solutions.' CREATED='1756820829922' ID='ID_mf2lrg0ycxvb95wu0ql' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(651) (DD-WRL-002) Enterprise Architect
Develops and maintains business, systems, and information processes to support enterprise mission needs; develops information technology (IT) rules and requirements that describe baseline and target architectures. ' CREATED='1756820829922' ID='ID_mf2lrg0y8mns6rcdkx7' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(661) (DD-WRL-008) Research &amp; Development Specialist
Conducts software and systems engineering and software systems research in order to develop new capabilities, ensuring cybersecurity is fully integrated. Conducts comprehensive technology research to evaluate potential vulnerabilities in cyberspace systems.' CREATED='1756820829922' ID='ID_mf2lrg0y1goo3fhtc9d' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(671) DD-WRL-007 System Testing and Evaluation Specialist
Plans, prepares, and executes tests of systems to evaluate results against specifications and requirements as well as analyze/report test results.' CREATED='1756820829922' ID='ID_mf2lrg0y66r0f6kbsfm' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Cybersecurity
(CS)
Personnel who secure, defend, and preserve data, networks, net-centric capabilities, and other designated systems by ensuring appropriate security controls and measures are in place, and taking internal defense actions. This includes access to system controls, monitoring, administration, and integration of cybersecurity into all aspects of engineering and acquisition of cyberspace capabilities.' CREATED='1756820829922' ID='ID_mf2lrg0yjlxbt1uqckq' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='OVERSIGHT and GOVERNANCE (OG) – Provides leadership, management, direction, and advocacy so the organization may effectively manage cybersecurity-related risks to the enterprise and conduct cybersecurity work. ' CREATED='1756820829922' ID='ID_mf2lrg0yw8qid3b7jr' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(611) (OG-WRL-013) Authorizing Official/Designated Representative 
Senior official or executive with the authority to formally assume responsibility for operating an information system at an acceptable level of risk to organizational operations (including mission, functions, image, or reputation), organizational assets, individuals, other organizations, and the Nation (CNSSI 4009).' CREATED='1756820829922' ID='ID_mf2lrg0yn9l1d7d8vo' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(612) (OG-WRL-012) Security Control Assessor
Conducts independent comprehensive assessments of the management, operational, and technical security controls and control enhancements employed within or inherited by an information technology (IT) system to determine the overall effectiveness of the controls (as defined in NIST 800-37). ' CREATED='1756820829922' ID='ID_mf2lrg0y1o6i7yd7ci6' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(722) (OG-WRL-014) Information Systems Security Manager
Responsible for the cybersecurity of a program, organization, system, or enclave. ' CREATED='1756820829922' ID='ID_mf2lrg0yrakgj6hxz3' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(723) (OG-WRL-001) COMSEC Manager 
Manages the Communications Security (COMSEC) resources of an organization (CNSSI No. 4009).' CREATED='1756820829922' ID='ID_mf2lrg0ys3k7fsubhbo' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='DESIGN and DEVELOPMENT (DD) – Conducts research, conceptualizes, designs, develops, and tests secure technology systems, including on perimeter and cloud-based networks. ' CREATED='1756820829922' ID='ID_mf2lrg0yif71x17vn7o' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(622) (DD-WRL-005) Secure Software Assessor
Analyzes the security of new or existing computer applications, software, or specialized utility programs and provides actionable results.' CREATED='1756820829922' ID='ID_mf2lrg0ydfg3j9fqp7' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(631) (DD-WRL-004) Information Systems Security Developer
Designs, develops, tests, and evaluates information system security throughout the systems development lifecycle.' CREATED='1756820829922' ID='ID_mf2lrg0y2by684fp2hl' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(652) (DD-WRL-001) Security Architect
Designs enterprise and systems security throughout the development lifecycle; translates technology and environmental conditions (e.g., law and regulation) into security designs and processes.' CREATED='1756820829922' ID='ID_mf2lrg0ytoten4ri15h' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(TBD-B) (DD-WRL-009)
Responsible for working within the engineering department to design and create systems, processes, and procedures that maintain the safety, reliability, controllability, and security of industrial systems in the face of intentional and incidental cyber events. Interfaces with Chief Information Security Officer, plant managers, and industrial cybersecurity technicians.' CREATED='1756820829922' ID='ID_mf2lrg0ykppzwmmm1l' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='PROTECTION and DEFENSE (PD) – Protects against, identifies, and analyzes risks to technology systems or networks. Includes investigation of cybersecurity events or crimes related to technology systems and networks.' CREATED='1756820829922' ID='ID_mf2lrg0yl0angrlkrxq' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(TBD-A) (PD-WRL-005) Insider Threat Analysis
Responsible for identifying and assessing the capabilities and activities of cybersecurity insider threats; produces findings to help initialize and support law enforcement and counterintelligence activities and investigations.' CREATED='1756820829922' ID='ID_mf2lrg0yjgcoshxgbr8' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(141) (PD-WRL-006)
Responsible for collecting, processing, analyzing, and disseminating cybersecurity threat/warning assessments. Develops cybersecurity indicators to maintain awareness of the status of the highly dynamic operating environment.' CREATED='1756820829922' ID='ID_mf2lrg0yy4owelktadk' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='Hors catégories NCWF' CREATED='1756820829922' ID='ID_mf2lrg0yhz0krmf6ht' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(462) (N/A) Control Systems Security Specialist
Responsible for device, equipment, and system-level cybersecurity configuration and day-to-day security operations of control systems, including security monitoring and maintenance along with stakeholder coordination to ensure the system and its interconnections are secure in support of mission operations.' CREATED='1756820829922' ID='ID_mf2lrg0y71a26f1fwpr' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Intel (Cyber)
(CI)
Personnel who collect, process, analyze, and disseminate information from all sources of intelligence on foreign actors’ cyberspace programs, intentions, capabilities, research and development, and operational activities.' CREATED='1756820829922' ID='ID_mf2lrg0yr56xw00mzxo' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='Hors catégories NCWF' CREATED='1756820829922' ID='ID_mf2lrg0y719x79ymdek' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(111) (N/A) All-Source Analyst 
Analyzes data/information from one or multiple sources to conduct preparation of the environment, respond to requests for information, and submit intelligence collection and production requirements in support of planning and operations. ' CREATED='1756820829922' ID='ID_mf2lrg0ycjezyguhjub' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(151) (N/A) Multi-Disciplined Language Analyst
Applies language and culture expertise with target/threat and technical knowledge to process, analyze, and/or disseminate intelligence information derived from language, voice and/or graphic material.  Creates, and maintains language specific databases and working aids to support cyber action execution and ensure critical knowledge sharing.  Provides subject matter expertise in foreign language-intensive or interdisciplinary projects.  ' CREATED='1756820829922' ID='ID_mf2lrg0yo5qm7f7qbwd' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(311) (N/A) All-Source Collection Manager
Identifies collection authorities and environment; incorporates priority information requirements into collection management; develops concepts to meet leadership&apos;s intent. Determines capabilities of available collection assets, identifies new collection capabilities; and constructs and disseminates collection plans.  Monitors execution of tasked collection to ensure effective execution of the collection plan.' CREATED='1756820829922' ID='ID_mf2lrg0yqj0b82ujrs' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(312) (N/A) All-Source Collection Requirements Manager
Evaluates collection operations and develops effects-based collection requirements strategies using available sources and methods to improve collection.  Develops, processes, validates, and coordinates submission of collection requirements.  Evaluates performance of collection assets and collection operations.' CREATED='1756820829922' ID='ID_mf2lrg0y23ud2yvtn5p' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(331) (N/A) Cyber Intelligence Planner
Develops detailed intelligence plans to satisfy cyber operations requirements.  Collaborates with cyber operations planners to identify, validate, and levy requirements for collection and analysis.  Participates in targeting selection, validation, synchronization, and execution of cyber actions.  Synchronizes intelligence activities to support organization objectives in cyberspace.' CREATED='1756820829922' ID='ID_mf2lrg0y3p01cc5zp5d' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Cyber Effects
(CE)
Personnel who plan, support, and execute cyberspace capabilities where the primary purpose is to externally defend or conduct force projection in or through cyberspace.' CREATED='1756820829922' ID='ID_mf2lrg0y4gvy6kvda9r' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='PROTECTION and DEFENSE (PD) – Protects against, identifies, and analyzes risks to technology systems or networks. Includes investigation of cybersecurity events or crimes related to technology systems and networks.' CREATED='1756820829922' ID='ID_mf2lrg0y45wpbxewwvm' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(141) (PD-WRL-006) 
Responsible for collecting, processing, analyzing, and disseminating cybersecurity threat/warning assessments. Develops cybersecurity indicators to maintain awareness of the status of the highly dynamic operating environment.' CREATED='1756820829922' ID='ID_mf2lrg0ytjajeslv6yk' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='Hors catégories NCWF' CREATED='1756820829922' ID='ID_mf2lrg0yaograajgpbr' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(112) (N/A) Mission Assessment Specialist
Develops assessment plans and measures of performance/effectiveness. Conducts strategic and operational effectiveness assessments as required for cyber events. Determines whether systems performed as expected and provides input to the determination of operational effectiveness.' CREATED='1756820829922' ID='ID_mf2lrg0yptqncg1r8h' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(121) (N/A) Exploitation Analyst
Partners with cyberspace operations customers to identify access and collection gaps that can be satisfied through cyberspace exploitation. Develops detailed plans that are executed by cyber operators. Functions as navigator in cyber operations. Uses all source data to understand cyberspace targets. Employs all available techniques against targeted networks. Identifies capability gaps and submits cyberspace capability requirements to capability development organizations.' CREATED='1756820829922' ID='ID_mf2lrg0y2zg001g8qr4' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(122) (N/A) Digital Network Exploitation Analyst
The DNEA analyzes intercepted intelligence information for metadata and content. They use this data to reconstruct and document target networks to judge the intelligence value and maintain target continuity. DNEAs understand and analyze target implementation of communication technologies and digital network systems. They discover methods and suggest strategies to exploit specific target networks, computer systems, or specific hardware and/or software.' CREATED='1756820829922' ID='ID_mf2lrg0y7y7ch103tgt' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(131) (N/A) Joint Targeting Analyst
Joint Targeting Analyst conduct target development at the system, component and entity levels. Builds and maintains Electronic Target Folders (ETFs), to include inputs from JIPOE, Target System Analysis (TSA), GMI and other IC sources. Senior analysts run collaborative target working groups across Geographic Combatant Commands (GCCs) and IC members, and present candidate targets for IC vetting and commander’s approval for inclusion on target lists. JTAs assess damage resulting from the application of lethal or non-lethal military force, and write Battle Damage Assessment (BDA) reports and coordinate federated support as required.' CREATED='1756820829922' ID='ID_mf2lrg0y64qe21de8f5' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(132) (N/A) Target Digital Network Analyst
The TDNA conducts advanced analysis of collection and open-source data to ensure target continuity, profile targets and their activities, and develop techniques to gain more target cyberspace operations related information. They possess knowledge of target cyberspace technologies and apply skills and knowledge of cyberspace networks and the applications on them to determine how targets communicate, move, operate, and live within the cyberspace domain. TDNAs apply analytical techniques to review relevant content carried in target cyberspace communications. The TDNA uses data from networks of all forms for target development. TDNAs are technology savvy and can be flexible enough to rapidly shift from one target to another.' CREATED='1756820829922' ID='ID_mf2lrg0yad3y207n1v' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(133) (N/A) Target Analyst Reporter
The Target Analyst Reporter (TAR) provides synthesized products to customers by researching, analyzing, and reporting intelligence via appropriate reporting vehicles in response to customer requirements and IAW missions of SIGINT, cybersecurity, and cyberspace operations. They prioritize, assess, evaluate, and report information obtained from SIGINT collection, cyber surveillance, and reconnaissance operations sources. The TAR enhances reporting with collateral information as required, maintains awareness of internal and external customer requirements, and collaborates with other collectors and analysts to refine collection and reporting requirements. The TAR shares target-related information and provides feedback to customers as appropriate. The TAR develops working aids and provides database updates on target activity to enhance and build target knowledge and improve collection. The TAR performs quality control and product-release functions.' CREATED='1756820829922' ID='ID_mf2lrg0yw63vqsvcmmm' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(321) (N/A) Access Network Operator
Conducts access collection, processing, and/or geolocation of wired or wireless computer and digital networks in order to exploit, locate, and/or track targets of interest.' CREATED='1756820829922' ID='ID_mf2lrg0y1f4qvdo9214' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(322) (N/A) Cyberspace Operator
Cyberspace Operators use a wide range of software applications for network navigation, tactical forensic analysis, surveillance and reconnaissance, and executing on-net operations in support of offensive cyberspace operations when directed.' CREATED='1756820829922' ID='ID_mf2lrg0yko1xau6wed' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(332) (N/A) Cyber Operations Planner
The Cyberspace Operations Planner applies in-depth knowledge of the JOPP to develop detailed plans and orders supporting CCMD cyberspace operation requirements. Uses Joint, Service, and interagency planning and operational experience to conduct strategic and operational level planning across the full range of military operations for integrated information and cyberspace operations. Develops and maintains deliberate and crisis action planning products. Collaborates with cyberspace operators to identify and levy requirements for intelligence collection and analysis. Participates in targeting selection, validation, synchronization, and execution of complex cyberspace operations. Has sufficient technical knowledge to understand cyberspace operations capabilities, target vulnerabilities, and effects. Collaborates with cyberspace operators, analysts, enablers and planners to gain access and technical intelligence to meet planning objectives.' CREATED='1756820829922' ID='ID_mf2lrg0yhyceylxct8u' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(333) (N/A) Partner integration Planner
Works to advance cooperation across organizational or national borders between cyber operations partners. Aids the integration of cyber partner teams by providing guidance, resources, and collaboration to develop best practices and facilitate organizational support for achieving objectives in integrated cyber actions.' CREATED='1756820829922' ID='ID_mf2lrg0yh9ym221pe5h' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(341) (N/A) Cyberspace Capability Developer
Provides software and hardware capabilities that produce cyberspace effects in and throughout cyberspace operations through vulnerability analysis, and software research and development.' CREATED='1756820829922' ID='ID_mf2lrg0ye1v8pz4m0hw' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(442) (N/A) Network Technician
The Network Technician provides enterprise and tactical infrastructure knowledge, experience, and integration to the Cyber Protection Team (CPT).  The Network Technician supports CPT elements by understanding of network technologies, defining mission scope, and identifying terrain.' CREATED='1756820829922' ID='ID_mf2lrg0ybqa84ezpgqn' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(443) (N/A) Network Analyst
The Network Analyst (NA) will understand network traffic signatures and discover anomalies through network traffic and packet capture (PCAP) analysis. The Network Analyst will identify, assess, and mitigate intrusions into networks that are vital to cyberspace operations security. Network Analysts also use GUI or command-line based tools and assist in developing network mapping and signatures. Network Analysts will develop advanced network detection rules and alerts, queries and dashboards to gain a holistic view of the network.' CREATED='1756820829922' ID='ID_mf2lrg0y057k1y70rj38' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(463) (N/A) Host Analyst
A Host Analyst (HA) will have knowledge of various system configurations encountered. This work role also performs analysis using built-in tools and capabilities. A Host Analyst will have knowledge of system services and the security and configuration of them, as well as knowledge of file systems, permissions, and operation system configurations. The Host Analyst conducts analysis using built-in tools and capabilities.' CREATED='1756820829922' ID='ID_mf2lrg0y2ji5lrw59w2' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(551) (N/A) Red Team Specialist
Leverages tools, systems, and utilities necessary to enhance the security posture of an organization, conducts threat and risk assessments, and performs testing and evaluation in accordance with legal and organizational requirements, policies, and regulations.' CREATED='1756820829922' ID='ID_mf2lrg0yfzawtaxs35h' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Data/AI
(DA)
Personnel who drive and support data, analytic, and AI-enabled capabilities that harness information for decision-advantage.' CREATED='1756820829922' ID='ID_mf2lrg0y17jjqcd4vjki' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='IMPLEMENTATION and OPERATION (IO) – Provides implementation, administration, configuration, operation, and maintenance to ensure effective and efficient technology system performance and security.' CREATED='1756820829922' ID='ID_mf2lrg0yrh6lom0vxq' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(422) (IO-WRL-001) Data Analyst
Analyzes and interprets data from multiple disparate sources and builds visualizations and dashboards to report insights' CREATED='1756820829922' ID='ID_mf2lrg0yajt8c6rtzpf' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='Hors catégories NCWF' CREATED='1756820829922' ID='ID_mf2lrg0yrf16qcjedl' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(423) (N/A) Data Scientist
&quot;Uncovers and explains actionable insights from data by combining scientific method, math and statistics, specialized programming, advanced analytics, AI, and storytelling.	&quot;' CREATED='1756820829922' ID='ID_mf2lrg0y67b1002bui' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(424) (N/A) Data Steward
Develops and maintains plans, policies, and processes for data management, data governance, security, quality, accessibility, use, and disposal. ' CREATED='1756820829922' ID='ID_mf2lrg0ycd9mnf1dm49' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(623) (N/A) AI/ML Specialist
Designs, develops, and modifies AI applications, tools, and/or other solutions to enable successful accomplishment of mission objectives.' CREATED='1756820829922' ID='ID_mf2lrg0y12aigwuh351r' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(624) (N/A) Data Operations Specialist
Builds, manages, and operationalizes data pipelines.' CREATED='1756820829922' ID='ID_mf2lrg0yo13kc9f4w0p' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(653) (N/A) Data Architect
Designs a system&apos;s data models, data flow, interfaces, and infrastructure to meet the information requirements of a business or mission.' CREATED='1756820829922' ID='ID_mf2lrg0ytj1v955cm4q' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(672) (N/A) AI Test &amp; Evaluation Specialist
Performs testing, evaluation, verification, and validation on AI solutions to ensure they are developed to be and remain robust, resilient, responsible, secure, and trustworthy; and communicates results and concerns to leadership.' CREATED='1756820829922' ID='ID_mf2lrg0y18jjllqopto' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(733) (N/A) AI Risk and Ethics Specialist
Educates those involved in the development of AI and conducts assessments on the technical and societal risks across the lifecycle of AI solutions from acquisition or design to deployment and use.' CREATED='1756820829922' ID='ID_mf2lrg0ymgo7bbgetwa' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(753) (N/A) AI Adoption Specialist
Facilitates AI adoption by supporting the users of AI-enabled solutions.' CREATED='1756820829922' ID='ID_mf2lrg0yu48lwws86u' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(902) (N/A) AI Innovation Leader
Builds the organization’s AI vision and plan and leads policy and doctrine formation, including how AI solutions can or will be used.' CREATED='1756820829922' ID='ID_mf2lrg0y5inyhbyhyk2' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(903) (N/A) Data Officer
Holds responsibility for developing, promoting, and overseeing implementation of data as an asset and the establishment and enforcement of data-related strategies, policies, standards, processes, and governance.' CREATED='1756820829922' ID='ID_mf2lrg0y5jbtxjkdjwb' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Software Engineering
(SE)
Personnel who manages and identifies program high-level technical specifications, which may include, application design, development, testing, deployment, cloud computing strategy and adoption, and integration of software applications into a functioning system to meet requirements.' CREATED='1756820829922' ID='ID_mf2lrg0y1agzqit221bh' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='DESIGN and DEVELOPMENT (DD) – Conducts research, conceptualizes, designs, develops, and tests secure technology systems, including on perimeter and cloud-based networks. ' CREATED='1756820829922' ID='ID_mf2lrg0yzv0twr5wmad' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(621) (DD-WRL-003) Software Developer 
Executes software planning, requirements, risk management, design, development, architecture, modeling, estimation, configuration management, quality, security, and tests using software development methodologies, architectural structures, viewpoints, styles, design decisions, and frameworks across all lifecycle phases. ' CREATED='1756820829922' ID='ID_mf2lrg0yx031gtrmt9n' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='IMPLEMENTATION and OPERATION (IO) – Provides implementation, administration, configuration, operation, and maintenance to ensure effective and efficient technology system performance and security.' CREATED='1756820829922' ID='ID_mf2lrg0yz50lpwxxie' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(461) (IO-WRL-006) Systems Security Analyst
Responsible for analysis and development of systems/software security through the product lifecycle to include integration, testing, operations and maintenance.' CREATED='1756820829922' ID='ID_mf2lrg0ya58y7g205ts' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='Hors catégories NCWF' CREATED='1756820829922' ID='ID_mf2lrg0yl8jd596utih' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(625) N/A) Product Designer User Interface (UI)
Manages the user interface design portion of the design process of a product.' CREATED='1756820829922' ID='ID_mf2lrg0yr3q0zekgei' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(626) (N/A) Service Designer User Experience (UX)
Manages the user interface design portion of the design process of a product.' CREATED='1756820829922' ID='ID_mf2lrg0ylpiv46pyz3' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(627) (N/A) DevSecOps Specialist
Selects/Deploys/Maintains the set of Continuous Integration/Continuous Deployment (CI/CD) tools and processes used by the development team and/or maintains the deployed software product and ensures observability and security across the lifecycle.' CREATED='1756820829922' ID='ID_mf2lrg0ym9yyf116dzg' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(628) (N/A) Software/Cloud Architect
Manages and identifies program high-level technical specifications, which may include application design, cloud computing strategy and adoption, and integration of software applications into a functioning system to meet requirements.' CREATED='1756820829922' ID='ID_mf2lrg0y5qiiaw2oq4e' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(673) (N/A) Software Test &amp; Evaluation Specialist
Plans, prepares, and performs testing, evaluation, verification, and validation of software to evaluate results against specifications, requirements, and operational need.' CREATED='1756820829922' ID='ID_mf2lrg0ygfvdwoc7xxv' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node><node TEXT='(806) (N/A) Product Manager
Manages the development of products including the resource management, product strategy (physical or digital), functional requirements, and releases. Coordinate work done by functions (like software engineers, data scientists, and product designers). ' CREATED='1756820829922' ID='ID_mf2lrg0y723fay321w5' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node><node TEXT='Sans Communauté
(CX)
Work roles pas encore attribués à un workforce element (DCWF community)' CREATED='1756820829922' ID='ID_mf2lrg0ypvlixx79nl' MODIFIED='1756820829922' POSITION='right'><depth>1</depth><icon/><image/><imageSize/><node TEXT='DESIGN and DEVELOPMENT (DD) – Conducts research, conceptualizes, designs, develops, and tests secure technology systems, including on perimeter and cloud-based networks. ' CREATED='1756820829922' ID='ID_mf2lrg0ybeaoyt11mbt' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(TBD-A) (PD-WRL-005) Insider Threat Analysis
Responsible for identifying and assessing the capabilities and activities of cybersecurity insider threats; produces findings to help initialize and support law enforcement and counterintelligence activities and investigations.' CREATED='1756820829922' ID='ID_mf2lrg0yhea6ju139x' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node><node TEXT='PROTECTION and DEFENSE (PD) – Protects against, identifies, and analyzes risks to technology systems or networks. Includes investigation of cybersecurity events or crimes related to technology systems and networks.' CREATED='1756820829922' ID='ID_mf2lrg0yt200y5azcub' MODIFIED='1756820829922'><depth>2</depth><icon/><image/><imageSize/><node TEXT='(TBD-B) (DD-WRL-009) Operational technology (OT) Cybersecurity Engineering
Responsible for working within the engineering department to design and create systems, processes, and procedures that maintain the safety, reliability, controllability, and security of industrial systems in the face of intentional and incidental cyber events. Interfaces with Chief Information Security Officer, plant managers, and industrial cybersecurity technicians.' CREATED='1756820829922' ID='ID_mf2lrg0yw1k35hfanc' MODIFIED='1756820829922'><depth>3</depth><icon/><image/><imageSize/></node></node></node></node></map>