from django.core.management.base import BaseCommand
from web_app.models.nice_framework_work_role import NiceFrameworkWorkRole

class Command(BaseCommand):
    help = 'Importer les données NICE Framework v2.0.0'

    def handle(self, *args, **options):
        # Données extraites de Efface.html
        roles_data = [
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Communications Security (COMSEC) Management', 'definition': 'Responsible for managing the Communications Security (COMSEC) resources of an organization.', 'nice_id': 'OG-WRL-001', 'opm_code': '723' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Cybersecurity Policy and Planning', 'definition': 'Responsible for developing and maintaining cybersecurity plans, strategy, and policy to support and align with organizational cybersecurity initiatives and regulatory compliance.', 'nice_id': 'OG-WRL-002', 'opm_code': '752' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Cybersecurity Workforce Management', 'definition': 'Responsible for developing cybersecurity workforce plans, assessments, strategies, and guidance, including cybersecurity-related staff training, education, and hiring processes. Makes adjustments in response to or in anticipation of changes to cybersecurity-related policy, technology, and staffing needs and requirements. Authors mandated workforce planning strategies to maintain compliance with legislation, regulation, and policy.', 'nice_id': 'OG-WRL-003', 'opm_code': '751' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Cybersecurity Curriculum Development', 'definition': 'Responsible for developing, planning, coordinating, and evaluating cybersecurity awareness, training, or education content, methods, and techniques based on instructional needs and requirements.', 'nice_id': 'OG-WRL-004', 'opm_code': '711' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Cybersecurity Instruction', 'definition': 'Responsible for developing and conducting cybersecurity awareness, training, or education.', 'nice_id': 'OG-WRL-005', 'opm_code': '712' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Cybersecurity Legal Advice', 'definition': 'Responsible for providing cybersecurity legal advice and recommendations, including monitoring related legislation and regulations.', 'nice_id': 'OG-WRL-006', 'opm_code': '731' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Executive Cybersecurity Leadership', 'definition': 'Responsible for establishing vision and direction for an organization\'s cybersecurity operations and resources and their impact on digital and physical spaces. Possesses authority to make and execute decisions that impact an organization broadly, including policy approval and stakeholder engagement.', 'nice_id': 'OG-WRL-007', 'opm_code': '901' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Privacy Compliance', 'definition': 'Responsible for developing and overseeing an organization\'s privacy compliance program and staff, including establishing and managing privacy-related governance, policy, and incident response needs.', 'nice_id': 'OG-WRL-008', 'opm_code': '732' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Product Support Management', 'definition': 'Responsible for planning, estimating costs, budgeting, developing, implementing, and managing product support strategies in order to field and maintain the readiness and operational capability of systems and components.', 'nice_id': 'OG-WRL-009', 'opm_code': '803' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Program Management', 'definition': 'Responsible for leading, coordinating, and the overall success of a defined program. Includes communicating about the program and ensuring alignment with agency or organizational priorities.', 'nice_id': 'OG-WRL-010', 'opm_code': '801' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Secure Project Management', 'definition': 'Responsible for overseeing and directly managing technology projects. Ensures cybersecurity is built into projects to protect the organization\'s critical infrastructure and assets, reduce risk, and meet organizational goals. Tracks and communicates project status and demonstrates project value to the organization.', 'nice_id': 'OG-WRL-011', 'opm_code': '802' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Security Control Assessment', 'definition': 'Responsible for conducting independent comprehensive assessments of management, operational, and technical security controls and control enhancements employed within or inherited by a system to determine their overall effectiveness.', 'nice_id': 'OG-WRL-012', 'opm_code': '612' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Systems Authorization', 'definition': 'Responsible for operating an information system at an acceptable level of risk to organizational operations, organizational assets, individuals, other organizations, and the nation.', 'nice_id': 'OG-WRL-013', 'opm_code': '611' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Systems Security Management', 'definition': 'Responsible for managing the cybersecurity of a program, organization, system, or enclave.', 'nice_id': 'OG-WRL-014', 'opm_code': '722' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Technology Portfolio Management', 'definition': 'Responsible for managing a portfolio of technology investments that align with the overall needs of mission and enterprise priorities.', 'nice_id': 'OG-WRL-015', 'opm_code': '801' },
            { 'category': 'OVERSIGHT and GOVERNANCE (OG)', 'title': 'Technology Program Auditing', 'definition': 'Responsible for conducting evaluations of technology programs or their individual components to determine compliance with published standards.', 'nice_id': 'OG-WRL-016', 'opm_code': '805' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Cybersecurity Architecture', 'definition': 'Responsible for ensuring that security requirements are adequately addressed in all aspects of enterprise architecture, including reference models, segment and solution architectures, and the resulting systems that protect and support organizational mission and business processes.', 'nice_id': 'DD-WRL-001', 'opm_code': '652' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Enterprise Architecture', 'definition': 'Responsible for developing and maintaining business, systems, and information processes to support enterprise mission needs. Develops technology rules and requirements that describe baseline and target architectures.', 'nice_id': 'DD-WRL-002', 'opm_code': '651' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Secure Software Development', 'definition': 'Responsible for developing, creating, modifying, and maintaining computer applications, software, or specialized utility programs.', 'nice_id': 'DD-WRL-003', 'opm_code': '621' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Secure Systems Development', 'definition': 'Responsible for the secure design, development, and testing of systems and the evaluation of system security throughout the systems development life cycle.', 'nice_id': 'DD-WRL-004', 'opm_code': '631 and 632' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Software Security Assessment', 'definition': 'Responsible for analyzing the security of new or existing computer applications, software, or specialized utility programs and delivering actionable results.', 'nice_id': 'DD-WRL-005', 'opm_code': '622' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Systems Requirements Planning', 'definition': 'Responsible for consulting with internal and external customers to evaluate and translate functional requirements and integrating security policies into technical solutions.', 'nice_id': 'DD-WRL-006', 'opm_code': '641' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Systems Testing and Evaluation', 'definition': 'Responsible for planning, preparing, and executing system tests; evaluating test results against specifications and requirements; and reporting test results and findings.', 'nice_id': 'DD-WRL-007', 'opm_code': '671' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Technology Research and Development', 'definition': 'Responsible for conducting software and systems engineering and software systems research to develop new capabilities with fully integrated cybersecurity. Conducts comprehensive technology research to evaluate potential vulnerabilities in cyberspace systems.', 'nice_id': 'DD-WRL-008', 'opm_code': '661' },
            { 'category': 'DESIGN and DEVELOPMENT (DD)', 'title': 'Operational Technology (OT) Cybersecurity Engineering', 'definition': 'Responsible for working within the engineering department to design and create systems, processes, and procedures that maintain the safety, reliability, controllability, and security of industrial systems in the face of intentional and incidental cyber-related events. Interfaces with Chief Information Security Officer, plant managers, and industrial cybersecurity technicians.', 'nice_id': 'DD-WRL-009', 'opm_code': 'TBD' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Data Analysis', 'definition': 'Responsible for analyzing data from multiple disparate sources to provide cybersecurity and privacy insight. Designs and implements custom algorithms, workflow processes, and layouts for complex, enterprise-scale data sets used for modeling, data mining, and research purposes.', 'nice_id': 'IO-WRL-001', 'opm_code': '422' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Database Administration', 'definition': 'Responsible for administering databases and data management systems that allow for the secure storage, query, protection, and utilization of data.', 'nice_id': 'IO-WRL-002', 'opm_code': '421' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Knowledge Management', 'definition': 'Responsible for managing and administering processes and tools to identify, document, and access an organization\'s intellectual capital.', 'nice_id': 'IO-WRL-003', 'opm_code': '431' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Network Operations', 'definition': 'Responsible for planning, implementing, and operating network services and systems, including hardware and virtual environments.', 'nice_id': 'IO-WRL-004', 'opm_code': '441' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Systems Administration', 'definition': 'Responsible for setting up and maintaining a system or specific components of a system in adherence with organizational security policies and procedures. Includes hardware and software installation, configuration, and updates; user account management; backup and recovery management; and security control implementation.', 'nice_id': 'IO-WRL-005', 'opm_code': '451' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Systems Security Analysis', 'definition': 'Responsible for developing and analyzing the integration, testing, operations, and maintenance of systems security. Prepares, performs, and manages the security aspects of implementing and operating a system.', 'nice_id': 'IO-WRL-006', 'opm_code': '461' },
            { 'category': 'IMPLEMENTATION and OPERATION (IO)', 'title': 'Technical Support', 'definition': 'Responsible for providing technical support to customers who need assistance utilizing client-level hardware and software in accordance with established or approved organizational policies and processes.', 'nice_id': 'IO-WRL-007', 'opm_code': '411' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Defensive Cybersecurity', 'definition': 'Responsible for analyzing data collected from various cybersecurity defense tools to mitigate risks.', 'nice_id': 'PD-WRL-001', 'opm_code': '511' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Digital Forensics', 'definition': 'Responsible for analyzing digital evidence from computer security incidents to derive useful information in support of system and network vulnerability mitigation.', 'nice_id': 'PD-WRL-002', 'opm_code': '212' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Incident Response', 'definition': 'Responsible for investigating, analyzing, and responding to network cybersecurity incidents.', 'nice_id': 'PD-WRL-003', 'opm_code': '531' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Infrastructure Support', 'definition': 'Responsible for testing, implementing, deploying, maintaining, and administering infrastructure hardware and software for cybersecurity.', 'nice_id': 'PD-WRL-004', 'opm_code': '521' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Insider Threat Analysis', 'definition': 'Responsible for identifying and assessing the capabilities and activities of cybersecurity insider threats; produces findings to help initialize and support law enforcement and counterintelligence activities and investigations.', 'nice_id': 'PD-WRL-005', 'opm_code': 'TBD' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Threat Analysis', 'definition': 'Responsible for collecting, processing, analyzing, and disseminating cybersecurity threat assessments. Develops cybersecurity indicators to maintain awareness of the status of the highly dynamic operating environment.', 'nice_id': 'PD-WRL-006', 'opm_code': '141' },
            { 'category': 'PROTECTION and DEFENSE (PD)', 'title': 'Vulnerability Analysis', 'definition': 'Responsible for assessing systems and networks to identify deviations from acceptable configurations, enclave policy, or local policy. Measure effectiveness of defense-in-depth architecture against known vulnerabilities.', 'nice_id': 'PD-WRL-007', 'opm_code': '541' },
            { 'category': 'INVESTIGATION (IN)', 'title': 'Cybercrime Investigation', 'definition': 'Responsible for investigating cyberspace intrusion incidents and crimes. Applies tactics, techniques, and procedures for a full range of investigative tools and processes and appropriately balances the benefits of prosecution versus intelligence gathering.', 'nice_id': 'IN-WRL-001', 'opm_code': '221' },
            { 'category': 'INVESTIGATION (IN)', 'title': 'Digital Evidence Analysis', 'definition': 'Responsible for identifying, collecting, examining, and preserving digital evidence using controlled and documented analytical and investigative techniques.', 'nice_id': 'IN-WRL-002', 'opm_code': '211' }
        ]

        # Supprimer les données existantes
        NiceFrameworkWorkRole.objects.all().delete()
        self.stdout.write(self.style.SUCCESS('Données existantes supprimées'))

        # Créer les nouvelles données
        created_count = 0
        for role_data in roles_data:
            role = NiceFrameworkWorkRole.objects.create(
                category=role_data['category'],
                title=role_data['title'],
                definition=role_data['definition'],
                nice_id=role_data['nice_id'],
                opm_code=role_data['opm_code']
            )
            created_count += 1
            self.stdout.write(f'Créé: {role.nice_id} - {role.title}')

        self.stdout.write(
            self.style.SUCCESS(f'Import terminé avec succès ! {created_count} work roles créés.')
        )
