# Generated by Django 5.1.6 on 2025-03-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DcwfCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ncwf2017Ksat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncwf_id", models.CharField(max_length=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Opm",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DcwfKsat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dcwf_id", models.CharField(max_length=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(max_length=20)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "ncwf_2017_ksats",
                    models.ManyToManyField(
                        blank=True, related_name="dcwf_ksats", to="web_app.ncwf2017ksat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ncwf2024Tks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncwf_id", models.CharField(max_length=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("category", models.CharField(max_length=20)),
                (
                    "ncwf_2017_ksats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ncwf_2024_tks",
                        to="web_app.ncwf2017ksat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ncwf2024WorkRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nist_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "ncwf_2024_tks",
                    models.ManyToManyField(blank=True, to="web_app.ncwf2024tks"),
                ),
                (
                    "opms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ncwf_2024_work_roles",
                        to="web_app.opm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ncwf2017WorkRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nist_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "ncwf_2017_ksats",
                    models.ManyToManyField(blank=True, to="web_app.ncwf2017ksat"),
                ),
                (
                    "ncwf_2024_workroles",
                    models.ManyToManyField(blank=True, to="web_app.ncwf2024workrole"),
                ),
                (
                    "opms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ncwf_2017_work_roles",
                        to="web_app.opm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DcwfWorkRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nist_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dcwf_work_roles",
                        to="web_app.dcwfcategory",
                    ),
                ),
                (
                    "dcwf_ksats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dcwf_work_roles",
                        to="web_app.dcwfksat",
                    ),
                ),
                (
                    "opm",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.opm",
                    ),
                ),
            ],
        ),
    ]
