# Continuer avec les autres communautés

# INTEL (CYBER) (CI) - 5 work roles
ci_roles = [
    # Hors catégories NCWF (tous N/A)
    ("CI", "111", "N/A", "All-Source Analyst", "Analyzes data/information from one or multiple sources to conduct preparation of the environment, respond to requests for information, and submit intelligence collection and production requirements in support of planning and operations."),
    ("CI", "151", "N/A", "Multi-Disciplined Language Analyst", "Applies language and culture expertise with target/threat and technical knowledge to process, analyze, and/or disseminate intelligence information derived from language, voice and/or graphic material. Creates, and maintains language specific databases and working aids to support cyber action execution and ensure critical knowledge sharing. Provides subject matter expertise in foreign language-intensive or interdisciplinary projects."),
    ("CI", "311", "N/A", "All-Source Collection Manager", "Identifies collection authorities and environment; incorporates priority information requirements into collection management; develops concepts to meet leadership's intent. Determines capabilities of available collection assets, identifies new collection capabilities; and constructs and disseminates collection plans. Monitors execution of tasked collection to ensure effective execution of the collection plan."),
    ("CI", "312", "N/A", "All-Source Collection Requirements Manager", "Evaluates collection operations and develops effects-based collection requirements strategies using available sources and methods to improve collection. Develops, processes, validates, and coordinates submission of collection requirements. Evaluates performance of collection assets and collection operations."),
    ("CI", "331", "N/A", "Cyber Intelligence Planner", "Develops detailed intelligence plans to satisfy cyber operations requirements. Collaborates with cyber operations planners to identify, validate, and levy requirements for collection and analysis. Participates in targeting selection, validation, synchronization, and execution of cyber actions. Synchronizes intelligence activities to support organization objectives in cyberspace."),
]

# CYBER EFFECTS (CE) - 16 work roles
ce_roles = [
    # PROTECTION and DEFENSE (PD)
    ("CE", "141", "PD-WRL-006", "Threat/Warning Analyst", "Responsible for collecting, processing, analyzing, and disseminating cybersecurity threat/warning assessments. Develops cybersecurity indicators to maintain awareness of the status of the highly dynamic operating environment."),
    # Hors catégories NCWF
    ("CE", "112", "N/A", "Mission Assessment Specialist", "Develops assessment plans and measures of performance/effectiveness. Conducts strategic and operational effectiveness assessments as required for cyber events. Determines whether systems performed as expected and provides input to the determination of operational effectiveness."),
    ("CE", "121", "N/A", "Exploitation Analyst", "Partners with cyberspace operations customers to identify access and collection gaps that can be satisfied through cyberspace exploitation. Develops detailed plans that are executed by cyber operators. Functions as navigator in cyber operations. Uses all source data to understand cyberspace targets. Employs all available techniques against targeted networks. Identifies capability gaps and submits cyberspace capability requirements to capability development organizations."),
    ("CE", "122", "N/A", "Digital Network Exploitation Analyst", "The DNEA analyzes intercepted intelligence information for metadata and content. They use this data to reconstruct and document target networks to judge the intelligence value and maintain target continuity. DNEAs understand and analyze target implementation of communication technologies and digital network systems. They discover methods and suggest strategies to exploit specific target networks, computer systems, or specific hardware and/or software."),
    ("CE", "131", "N/A", "Joint Targeting Analyst", "Joint Targeting Analyst conduct target development at the system, component and entity levels. Builds and maintains Electronic Target Folders (ETFs), to include inputs from JIPOE, Target System Analysis (TSA), GMI and other IC sources. Senior analysts run collaborative target working groups across Geographic Combatant Commands (GCCs) and IC members, and present candidate targets for IC vetting and commander's approval for inclusion on target lists. JTAs assess damage resulting from the application of lethal or non-lethal military force, and write Battle Damage Assessment (BDA) reports and coordinate federated support as required."),
    ("CE", "132", "N/A", "Target Digital Network Analyst", "The TDNA conducts advanced analysis of collection and open-source data to ensure target continuity, profile targets and their activities, and develop techniques to gain more target cyberspace operations related information. They possess knowledge of target cyberspace technologies and apply skills and knowledge of cyberspace networks and the applications on them to determine how targets communicate, move, operate, and live within the cyberspace domain. TDNAs apply analytical techniques to review relevant content carried in target cyberspace communications. The TDNA uses data from networks of all forms for target development. TDNAs are technology savvy and can be flexible enough to rapidly shift from one target to another."),
    ("CE", "133", "N/A", "Target Analyst Reporter", "The Target Analyst Reporter (TAR) provides synthesized products to customers by researching, analyzing, and reporting intelligence via appropriate reporting vehicles in response to customer requirements and IAW missions of SIGINT, cybersecurity, and cyberspace operations. They prioritize, assess, evaluate, and report information obtained from SIGINT collection, cyber surveillance, and reconnaissance operations sources. The TAR enhances reporting with collateral information as required, maintains awareness of internal and external customer requirements, and collaborates with other collectors and analysts to refine collection and reporting requirements. The TAR shares target-related information and provides feedback to customers as appropriate. The TAR develops working aids and provides database updates on target activity to enhance and build target knowledge and improve collection. The TAR performs quality control and product-release functions."),
    ("CE", "321", "N/A", "Access Network Operator", "Conducts access collection, processing, and/or geolocation of wired or wireless computer and digital networks in order to exploit, locate, and/or track targets of interest."),
    ("CE", "322", "N/A", "Cyberspace Operator", "Cyberspace Operators use a wide range of software applications for network navigation, tactical forensic analysis, surveillance and reconnaissance, and executing on-net operations in support of offensive cyberspace operations when directed."),
    ("CE", "332", "N/A", "Cyber Operations Planner", "The Cyberspace Operations Planner applies in-depth knowledge of the JOPP to develop detailed plans and orders supporting CCMD cyberspace operation requirements. Uses Joint, Service, and interagency planning and operational experience to conduct strategic and operational level planning across the full range of military operations for integrated information and cyberspace operations. Develops and maintains deliberate and crisis action planning products. Collaborates with cyberspace operators to identify and levy requirements for intelligence collection and analysis. Participates in targeting selection, validation, synchronization, and execution of complex cyberspace operations. Has sufficient technical knowledge to understand cyberspace operations capabilities, target vulnerabilities, and effects. Collaborates with cyberspace operators, analysts, enablers and planners to gain access and technical intelligence to meet planning objectives."),
    ("CE", "333", "N/A", "Partner Integration Planner", "Works to advance cooperation across organizational or national borders between cyber operations partners. Aids the integration of cyber partner teams by providing guidance, resources, and collaboration to develop best practices and facilitate organizational support for achieving objectives in integrated cyber actions."),
    ("CE", "341", "N/A", "Cyberspace Capability Developer", "Provides software and hardware capabilities that produce cyberspace effects in and throughout cyberspace operations through vulnerability analysis, and software research and development."),
    ("CE", "442", "N/A", "Network Technician", "The Network Technician provides enterprise and tactical infrastructure knowledge, experience, and integration to the Cyber Protection Team (CPT). The Network Technician supports CPT elements by understanding of network technologies, defining mission scope, and identifying terrain."),
    ("CE", "443", "N/A", "Network Analyst", "The Network Analyst (NA) will understand network traffic signatures and discover anomalies through network traffic and packet capture (PCAP) analysis. The Network Analyst will identify, assess, and mitigate intrusions into networks that are vital to cyberspace operations security. Network Analysts also use GUI or command-line based tools and assist in developing network mapping and signatures. Network Analysts will develop advanced network detection rules and alerts, queries and dashboards to gain a holistic view of the network."),
    ("CE", "463", "N/A", "Host Analyst", "A Host Analyst (HA) will have knowledge of various system configurations encountered. This work role also performs analysis using built-in tools and capabilities. A Host Analyst will have knowledge of system services and the security and configuration of them, as well as knowledge of file systems, permissions, and operation system configurations. The Host Analyst conducts analysis using built-in tools and capabilities."),
    ("CE", "551", "N/A", "Red Team Specialist", "Leverages tools, systems, and utilities necessary to enhance the security posture of an organization, conducts threat and risk assessments, and performs testing and evaluation in accordance with legal and organizational requirements, policies, and regulations."),
]

print(f"✅ CI: {len(ci_roles)} work roles")
print(f"✅ CE: {len(ce_roles)} work roles")

# Continuer avec DATA/AI et SOFTWARE ENGINEERING
total_so_far += len(ci_roles) + len(ce_roles)
print(f"Total jusqu'ici: {total_so_far}")