# Generated by Django 5.1.6 on 2025-03-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_dcwfcategory_ncwf2017ksat_opm_dcwfksat_ncwf2024tks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dcwfksat",
            name="ncwf_2017_ksats",
        ),
        migrations.AddField(
            model_name="dcwfksat",
            name="ncwf_2017_ksat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dcwf_ksats",
                to="web_app.ncwf2017ksat",
            ),
            preserve_default=False,
        ),
    ]
