# Generated by Django 5.1.6 on 2025-03-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_remove_dcwfworkrole_dcwf_ksats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DcwfWorkRoleKsatRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CORE", "Core"), ("ADDITIONAL", "Additional")],
                        max_length=10,
                    ),
                ),
                (
                    "dcwf_ksat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.dcwfksat",
                    ),
                ),
                (
                    "dcwf_work_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.dcwfworkrole",
                    ),
                ),
            ],
            options={
                "unique_together": {("dcwf_work_role", "dcwf_ksat")},
            },
        ),
    ]
