# Generated by Django 5.1.6 on 2025-03-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0005_dcwfworkroleksatrelation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dcwfworkroleksatrelation",
            unique_together={("dcwf_work_role", "dcwf_ksat", "type")},
        ),
    ]
