# Generated by Django 5.1.6 on 2025-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0006_alter_dcwfworkroleksatrelation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="dcwfcategory",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
