# Generated by Django 5.2 on 2025-05-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_dcwfcategory_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dcwfworkroleksatrelation',
            name='dcwf_ksat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcwf_work_role_relations', to='web_app.dcwfksat'),
        ),
        migrations.AlterField(
            model_name='dcwfworkroleksatrelation',
            name='dcwf_work_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcwf_ksat_relations', to='web_app.dcwfworkrole'),
        ),
        migrations.AlterField(
            model_name='ncwf2017workrole',
            name='ncwf_2017_ksats',
            field=models.ManyToManyField(blank=True, related_name='ncwf_2017_work_roles', to='web_app.ncwf2017ksat'),
        ),
        migrations.AlterField(
            model_name='ncwf2024workrole',
            name='ncwf_2024_tks',
            field=models.ManyToManyField(blank=True, related_name='ncwf_2024_work_roles', to='web_app.ncwf2024tks'),
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='web_app.selectcategory')),
                ('ksat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='web_app.ksattype')),
            ],
            options={
                'ordering': ['category', 'ksat_type', 'order'],
                'unique_together': {('category', 'ksat_type', 'value')},
            },
        ),
    ]
