# Generated by Django 5.2 on 2025-05-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_ksattype_selectcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalInfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ksat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_infos', to='web_app.ksattype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_infos', to='web_app.modalinfocategory')),
            ],
            options={
                'unique_together': {('category', 'ksat_type')},
            },
        ),
        migrations.CreateModel(
            name='ModalInfoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('modal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='web_app.modalinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
