# Generated by Django 5.2 on 2025-06-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_user_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clé de stockage (équivalent à la clé du localStorage)', max_length=255)),
                ('value', models.JSONField(help_text='Valeur associée à la clé (stockée en JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Données sauvegardées utilisateur',
                'verbose_name_plural': 'Données sauvegardées utilisateurs',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
