# Generated by Django 5.2 on 2025-08-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_usersaveddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcwf2025Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie DCWF 2025',
                'verbose_name_plural': 'Catégories DCWF 2025',
            },
        ),
        migrations.CreateModel(
            name='Dcwf2025WorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcwf_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ncwf_id', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_roles', to='web_app.dcwf2025category')),
            ],
            options={
                'verbose_name': 'Work Role DCWF 2025',
                'verbose_name_plural': 'Work Roles DCWF 2025',
                'ordering': ['dcwf_code'],
            },
        ),
    ]
