# Generated by Django 5.2 on 2025-08-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_dcwf2025category_dcwf2025workrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceFrameworkWorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OVERSIGHT and GOVERNANCE (OG)', 'OVERSIGHT and GOVERNANCE (OG)'), ('DESIGN and DEVELOPMENT (DD)', 'DESIGN and DEVELOPMENT (DD)'), ('IMPLEMENTATION and OPERATION (IO)', 'IMPLEMENTATION and OPERATION (IO)'), ('PROTECTION and DEFENSE (PD)', 'PROTECTION and DEFENSE (PD)'), ('INVESTIGATION (IN)', 'INVESTIGATION (IN)')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('nice_id', models.CharField(max_length=20, unique=True)),
                ('opm_code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['category', 'nice_id'],
            },
        ),
    ]
