# Generated by Django 5.2 on 2025-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_niceframeworkworkrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcwf2025workrole',
            name='ncwf_definition',
            field=models.TextField(blank=True, help_text='Définition NCWF 2025', null=True),
        ),
    ]
