# Generated by Django 5.2 on 2025-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_dcwf2025workrole_ncwf_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcwf2025workrole',
            name='ncwf_title',
            field=models.CharField(blank=True, help_text='Titre NCWF 2025', max_length=200, null=True),
        ),
    ]
