# Generated by Django 5.2 on 2025-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_dcwf2025workrole_ncwf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_user', 'Super User'), ('beta_tester', 'Bêta testeur'), ('normal_user', 'User Normal')], default='normal_user', help_text="Rôle de l'utilisateur déterminé automatiquement par le matricule", max_length=20),
        ),
    ]
