# Generated by Django 5.2 on 2025-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Emerging AI work roles with Real Impact (SANS)', max_length=100)),
            ],
        ),
    ]
