# Generated by Django 5.2 on 2025-09-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_aiworkrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ncwf2025Ksat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncwf_id', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=20)),
                ('core_or_additional', models.CharField(choices=[('C', 'Core'), ('A', 'Additional')], default='A', help_text='Core (C) ou Additional (A)', max_length=1)),
            ],
            options={
                'verbose_name': 'KSAT NCWF 2025',
                'verbose_name_plural': 'KSAT NCWF 2025',
                'ordering': ['ncwf_id'],
            },
        ),
        migrations.CreateModel(
            name='Ncwf2025WorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncwf_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('framework', models.CharField(default='NCWF', max_length=10)),
            ],
            options={
                'verbose_name': 'Work Role NCWF 2025',
                'verbose_name_plural': 'Work Roles NCWF 2025',
                'ordering': ['ncwf_id'],
            },
        ),
        migrations.CreateModel(
            name='Ncwf2025WorkRoleKsatRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_or_additional', models.CharField(choices=[('C', 'Core'), ('A', 'Additional')], default='A', help_text='Core (C) ou Additional (A)', max_length=1)),
                ('ksat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_role_relations', to='web_app.ncwf2025ksat')),
                ('work_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksat_relations', to='web_app.ncwf2025workrole')),
            ],
            options={
                'verbose_name': 'Relation Work Role NCWF 2025 - KSAT',
                'verbose_name_plural': 'Relations Work Role NCWF 2025 - KSAT',
                'unique_together': {('work_role', 'ksat')},
            },
        ),
    ]
