# Generated by Django 5.2 on 2025-09-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_ncwf2025ksat_ncwf2025workrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcwf2025Ksat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcwf_id', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=20)),
                ('core_or_additional', models.CharField(choices=[('C', 'Core'), ('A', 'Additional')], default='A', help_text='Core (C) ou Additional (A)', max_length=1)),
            ],
            options={
                'verbose_name': 'KSAT DCWF 2025',
                'verbose_name_plural': 'KSAT DCWF 2025',
                'ordering': ['dcwf_id'],
            },
        ),
        migrations.CreateModel(
            name='Dcwf2025WorkRoleKsatRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_or_additional', models.CharField(choices=[('C', 'Core'), ('A', 'Additional')], default='A', help_text='Core (C) ou Additional (A)', max_length=1)),
                ('ksat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_role_relations', to='web_app.dcwf2025ksat')),
                ('work_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksat_relations', to='web_app.dcwf2025workrole')),
            ],
            options={
                'verbose_name': 'Relation Work Role DCWF 2025 - KSAT',
                'verbose_name_plural': 'Relations Work Role DCWF 2025 - KSAT',
                'unique_together': {('work_role', 'ksat')},
            },
        ),
    ]
